layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

repositories:
  - GitLabAndroid
  - PixelCamera
  - Monologue
  - gmtk2025
  - PokeSavRBG
  - LiveViewLib
  - CoreBoy
  - UltrawideHelper
  - starch

topics:
  - name: C#
    web_url: https://github.com/topics/csharp
    image_url: https://raw.githubusercontent.com/github/explore/7f96d7ea34ea0b21f159792a6a8f43b716b33379/topics/csharp/csharp.png

  - name: Rust
    web_url: https://github.com/topics/rust
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/rust/rust.png

  - name: Godot
    web_url: https://github.com/topics/godot
    image_url: https://github.com/github/explore/blob/main/topics/godot/godot.png?raw=true

theme: jekyll-theme-minimal
